# Generated by Django 4.2.19 on 2025-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_devicedata_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
