# Generated by Django 4.2.19 on 2025-02-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_devicedata_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
