# Generated by Django 4.2.19 on 2025-02-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_devicedata_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
    ]
